server:
  port: 8080
  servlet:
    context-path: /angular
    session:
      timeout: 3000
      cookie:
        max-age: 3000
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cheng.angulardemo.entity

thymeleaf:
  cache: false

spring:
  datasource:
    url: jdbc:mysql://47.102.43.84:33061/angulartest?serverTimezone=GMT&useSSL=false&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: Changgongcheng00
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      type: com.alibaba.druid.pool.DruidDataSource
#如果没有引入thymeleaf包，则需要添加该配置，ModelAndView的默认目录为resource里的static
#  mvc:
#      view:
#        prefix: /
#        suffix: .html